### PR TITLE
compose initial readthedocs content

### PR DESCRIPTION
**Pull request by cantbewong**

### CODE REVIEW

**Comment by clintonskitson** [comment]
@cantbewong this should include the staged link for downloads.. we will have files there shortly as well

**Comment by clintonskitson** [comment]
```
mkdir -p ~/work/src/github.com/emccode
cd ~/work/src/github.com/emccode

**Comment by clintonskitson** [comment]
Here is a scaleio example for your docs.

```
polly:
  store:
    type: boltdb
    endpoints: /tmp/boltdb
    bucket: MyBoltDb_test
  libstorage:
    host: tcp://localhost:7981
    profiles:
      enabled: true
      groups:
      - local=127.0.0.1
    server:
      endpoints:
        localhost:
          address: tcp://localhost:7981
      services:
        mock:
          libstorage:
            driver: mock
        mock2:
          libstorage:
            driver: mock
        vfs:
          libstorage:
            driver: vfs
        scaleio:
          libstorage:
            driver: scaleio
          scaleio:
            endpoint: https://192.168.50.12/api
            insecure: true
            userName: admin
            password: Scaleio123
            systemName: cluster1
            protectionDomainName: pdomain
            storagePoolName: pool1
```

**Comment by clintonskitson** [comment]
We should also document the REX-Ray configuration needed (libstorage client) to talk to a remote Polly.

```
rexray:
  logLevel: debug
libstorage:
  logLevel: debug 
  host: tcp://127.0.0.1:7981
  service: scaleio
```

**Comment by clintonskitson** [comment]
`\etc\polly\config.yml` reall? =)

**Comment by clintonskitson** [comment]
How about pointing to your API docs?

**Comment by cantbewong** [comment]
Issues raised in review comments have been addressed in update to pull request

**Pull request merged**
