### PR TITLE
Enables the CI build to work for polly.

### PR DESCRIPTION
**Pull request by dvonthenen**
The bintray artifacts have been created.
The github service has been added to the repo.
core/core.go had to be renamed to core/polly.go to satisfy the build env.
Some artifacts that have been stubbed out have been created: example /test and /polly/cli these are only stubs enough to make the CI build work

### CODE REVIEW

**Comment by dvonthenen** [comment]
Yea, since I enabled the CI build for the repo... a build is going to take place but that isnt obviously going to work since I am checking in the files that the CI builds needs.

**Comment by dvonthenen** [comment]
Pooo..... looks like I need some help with this. The reason why this CI build fails is because the command "git describe --long --dirty" fails to grab a version number from the last annotated tag. I created one (0.0.1) that enabled it to work in my private repo, but it didnt seem to work in this repo. This is cause the filename and the RPM builds to fail.

**Comment by dvonthenen** [comment]
Thanks for the fix @clintonskitson

**Comment by clintonskitson** [comment]
Squash that pig!

**Comment by clintonskitson** [comment]
LGTM!

**Pull request merged**
